### ISSUE TITLE
Comment about screen reader support for <strong> or <em>

### ISSUE THREAD

**Issue by materreni** [learn-the-web/topics#24]
Screen readers never supported `<strong>` or `<em>`, I think it is something we all wanted to happen some day but it was never actually implemented (and maybe for good reasons, see comments on next paragraph for the case of other text-level tags):
https://www.tpgi.com/screen-readers-lack-emphasis/
https://freedomscientific.github.io/VFO-standards-support/html.html

NVDA had something like this enabled by default some years ago but now is an opt-in as `<strong>` seemed to be misused a lot and ended up been quite annoying for sr user. But it didn’t worked changing the tone of voice, it just said “bold” following the text:
https://github.com/nvaccess/nvda/issues/4920#issuecomment-155334599

Still, I think text-level elements like `<i>` are still better than `<span>` to indicate changes on speech language for screen readers, like `<i lang=“es”>Ricardo</i>`

By the way, amazing work!

**Comment by thomasjbradley** [comment]
That’s disappointing. I still think it’s a nice way to explain & to help new people understand the proposed semantics behind the tags.
